export const PAGE_NAMES = {
  ABOUT: "about",
  SKILLS: "skills",
  PROJECTS: "portfolio",
  CONTACT: "contact",
};

const BASE_PATH = "/pages";

const BASE_ABOUT_PATH = `${BASE_PATH}/${PAGE_NAMES.ABOUT}`;
const BASE_SKILLS_PATH = `${BASE_PATH}/${PAGE_NAMES.SKILLS}`;
const BASE_PROJECTS_PATH = `${BASE_PATH}/${PAGE_NAMES.PROJECTS}`;
const BASE_CONTACT_PATH = `${BASE_PATH}/${PAGE_NAMES.CONTACT}`;

export const LABELS = {
  ABOUT: "À propos",
  SKILLS: "Skills",
  PROJECTS: "Projets",
  CONTACT: "Me Contacter",
};

export const PROJECT_NAMES = {
  MYTODOLIST: "mytodolist",
  STUDENTS: "students",
  SERIES: "series",
  AUCTIONS: "auctions",
  LIC: "lic",
};

export const ROUTES = {
  HOME: "/#header",

  ABOUT_HOME: `#${PAGE_NAMES.ABOUT}home`,
  ABOUT_PATH: BASE_ABOUT_PATH,
  ABOUT_ANCHOR: `${BASE_ABOUT_PATH}#${PAGE_NAMES.ABOUT}`,

  SKILLS_HOME: `#${PAGE_NAMES.SKILLS}home`,
  SKILLS_PATH: BASE_SKILLS_PATH,
  SKILLS_ANCHOR: `${BASE_SKILLS_PATH}#${PAGE_NAMES.SKILLS}`,

  PROJECTS_HOME: "#projetshome",
  PROJECTS_PATH: BASE_PROJECTS_PATH,
  PROJECTS_ANCHOR: `${BASE_PROJECTS_PATH}#projets`,

  CONTACT_PATH: BASE_CONTACT_PATH,
  CONTACT_ANCHOR: `${BASE_CONTACT_PATH}#${PAGE_NAMES.CONTACT}`,

  PROJECTS: {
    MYTODOLIST: `${BASE_PROJECTS_PATH}#${PROJECT_NAMES.MYTODOLIST}`,
    STUDENTS: `${BASE_PROJECTS_PATH}#${PROJECT_NAMES.STUDENTS}`,
    SERIES: `${BASE_PROJECTS_PATH}#${PROJECT_NAMES.SERIES}`,
    AUCTIONS: `${BASE_PROJECTS_PATH}#${PROJECT_NAMES.AUCTIONS}`,
    LIC: `${BASE_PROJECTS_PATH}#${PROJECT_NAMES.LIC}`,
  },
};
