export const PAGE_NAMES = {
  ABOUT: "about",
  SKILLS: "skills",
  PROJECTS: "projets",
  CONTACT: "contact",
};

//const BASE_PATH = "/pages";

const BASE_ABOUT_PATH = `${PAGE_NAMES.ABOUT}`;
const BASE_SKILLS_PATH = `${PAGE_NAMES.SKILLS}`;
const BASE_PROJECTS_PATH = `${PAGE_NAMES.PROJECTS}`;
const BASE_CONTACT_PATH = `${PAGE_NAMES.CONTACT}`;

export const LABELS = {
  ABOUT: "À propos",
  SKILLS: "Skills",
  PROJECTS: "Projets",
  CONTACT: "Me Contacter",
};

export const PROJECT_NAMES = {
  MYTODOLIST: "mytodolist",
  STUDENTS: "students",
  SERIES: "series",
  AUCTIONS: "auctions",
  LIC: "lic",
};

export const ROUTES = {
  HOME: "/#header",

  ABOUT_HOME: `#${PAGE_NAMES.ABOUT}home`,
  ABOUT_PATH: `/${BASE_ABOUT_PATH}`,
  ABOUT_ANCHOR: `/${PAGE_NAMES.ABOUT}#${PAGE_NAMES.ABOUT}`,

  SKILLS_HOME: `#${PAGE_NAMES.SKILLS}home`,
  SKILLS_PATH: `/${BASE_SKILLS_PATH}`,
  SKILLS_ANCHOR: `/${PAGE_NAMES.SKILLS}#${PAGE_NAMES.SKILLS}`,

  PROJECTS_HOME: `#${PAGE_NAMES.PROJECTS}home`,
  PROJECTS_PATH: `/${BASE_PROJECTS_PATH}`,
  PROJECTS_ANCHOR: `/${PAGE_NAMES.PROJECTS}#${PAGE_NAMES.PROJECTS}`,

  CONTACT_PATH: `/${BASE_CONTACT_PATH}`,
  CONTACT_ANCHOR: `/${PAGE_NAMES.CONTACT}#${PAGE_NAMES.CONTACT}`,

  PROJECTS: {
    MYTODOLIST: `${BASE_PROJECTS_PATH}#${PROJECT_NAMES.MYTODOLIST}`,
    STUDENTS: `${BASE_PROJECTS_PATH}#${PROJECT_NAMES.STUDENTS}`,
    SERIES: `${BASE_PROJECTS_PATH}#${PROJECT_NAMES.SERIES}`,
    AUCTIONS: `${BASE_PROJECTS_PATH}#${PROJECT_NAMES.AUCTIONS}`,
    LIC: `${BASE_PROJECTS_PATH}#${PROJECT_NAMES.LIC}`,
  },
};
